### ISSUE TITLE
Get started instructions dont work.

### ISSUE THREAD

**Issue by chaluo** [Keyfactor/ejbca-easy-rest-client#7]
Hi.
I followed the get started instructions and got the error "Failed to execute goal on project erce: Could not resolve dependencies for project com.keyfactor:erce:jar:0.0.8-SNAPSHOT: Could not find artifact com.keyfactor:x509-common-util:jar:0.6.0-SNAPSHOT in local-maven-repo (file:////home/ch041142/projects/ejbca-easy-rest-client/lib) -> [Help 1]". 
Full error in the attached file.

I have attached a patch that makes alterations so it builds. It updates the x509-common-util local maven meta data and moves the jar to the (correct?) place. I am not sure if this is how its supposed to work but it builds now and seems to work.

Apply it by doing "git apply 0001-Fixed-sp-0.6.0-works.patch.txt"

[error.txt](https://github.com/Keyfactor/ejbca-easy-rest-client/files/12183021/error.txt)
[0001-Fixed-sp-0.6.0-works.patch.txt](https://github.com/Keyfactor/ejbca-easy-rest-client/files/12183048/0001-Fixed-sp-0.6.0-works.patch.txt)

**Comment by chaluo** [comment]
Nvm
Doesnt seem to work.
All i get is 

[ch041142@x]$ java -jar erce-0.0.8-SNAPSHOT.jar status --authkeystore /home/ch041142/Downloads/ECRE_admin.p12 --hostname st-infra-ejbca-01:8443
Exception in thread "main" java.lang.NullPointerException
	at com.keyfactor.ejbca.client.ErceCommandBase.stripSharedParameters(ErceCommandBase.java:161)
	at com.keyfactor.ejbca.client.ErceCommandBase.execute(ErceCommandBase.java:102)
	at org.ejbca.ui.cli.infrastructure.library.CommandLibrary$Branch.execute(CommandLibrary.java:289)
	at org.ejbca.ui.cli.infrastructure.library.CommandLibrary.findAndExecuteCommandFromParameters(CommandLibrary.java:68)
	at com.keyfactor.ejbca.client.ErceClient.main(ErceClient.java:32)
[ch041142@x]$

**Comment by primetomas** [comment]
Thanks. I actually noticed the same build issue before my vacation. I fixed it, upgraded libraries and pushed a new version.
I added an nice error message for the NullPointerException you encountered. It's because you need to either specify the password for the p12 file as a parameter, or ask to be prompted.
